name: build-and-publish
on:
  push:
    branches:
      - master
    tags:
      - 'v*'

  pull_request:
    branches:
      - master

jobs:
  build-dtool-pdf:
    uses: livMatS/RDM-Wiki-public/.github/workflows/build-dtool-pdf.yml@master

  publish-on-github:
    runs-on: ubuntu-20.04

    needs:
      - build-dtool-pdf

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Prepare
        run: |
          mkdir -p /tmp/dtool-pdf

      - name: Download dtool pdf
        uses: actions/download-artifact@v2
        with:
          name: dtool-pdf
          path: /tmp/dtool-pdf

      - name: List content of builds
        run: |
          ls -lhv /tmp/dtool-pdf/

      - name: Prepare and pack release assets
        run: |
          cp rdm/dtool/samples/dtool-external.json /tmp/dtool-pdf/dtool.json
          cp rdm/dtool/samples/dtool_readme.yml /tmp/dtool-pdf/dtool_readme.yml

          cd /tmp/dtool-pdf
          mv output.pdf dtool-guidelines-latest.pdf
          cp dtool-guidelines-latest.pdf dtool-guidelines-${{ steps.get_version.outputs.version }}.pdf

      - name: Make release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /tmp/dtool-pdf/dtool.json
            /tmp/dtool-pdf/dtool_readme.yml
            /tmp/dtool-pdf/dtool-guidelines-latest.pdf
            /tmp/dtool-pdf/dtool-guidelines-${{ steps.get_version.outputs.version }}.pdf
          draft: true
